const assets = `${import.meta.env?.BASE_URL ?? '/'}assets/planets`;

// Shared by the scrolling portfolio, planet previews, and project panels.
export const projects = [
  {
    id: 3, sequence: '01', projectInfo: 'Resource & Cost Tracker',
    previewDescription: 'Attributing infrastructure costs to product features.',
    category: 'Production engineering', kind: 'Booking.com internship', year: '2026',
    summary: 'Connecting Booking.com resource usage to the features and teams behind it.',
    description: 'Built and deployed Java instrumentation attributing CPU time and heap allocation to business features in a shared pricing service at Booking.com. Extended coverage across execution paths with deterministic tests and safeguards against double counting. Developed Grafana dashboards and a cost model reporting resource use and estimated monthly infrastructure cost by feature and team.',
    role: 'Software engineering intern', technologies: ['Java', 'Grafana', 'Instrumentation'],
    takeaway: 'Performance · Observability · Cost attribution', visual: 'metrics',
    accent: '#aaa0e6', featured: true,
    orbitalRadius: 10, orbitalSpeed: 0.15, visualRadius: 1.3,
    initialAngle: -1.0,
    modelPath: `${assets}/p-e48279ad.planet`,
  },
  {
    id: 5, sequence: '02', projectInfo: 'ResumAI',
    previewDescription: 'Turning experience into tailored professional CVs.',
    category: 'AI-assisted applications', kind: 'Codehive project', year: '2024–2026',
    summary: 'Helping teams turn hours of CV preparation into minutes.',
    description: 'Led development of an AI-assisted CV platform used by three companies. Built the React frontend, streaming generation, and visual template editor, and deployed document-processing workflows with Django, Celery, Redis, and PostgreSQL. Estimated preparation time fell from around three hours to ten minutes, including final edits.',
    role: 'Lead developer · Codehive', technologies: ['React', 'Django', 'Celery'],
    takeaway: 'Document processing · Streaming · Product development',
    accent: '#99c9df', featured: true,
    orbitalRadius: 16, orbitalSpeed: 0.10, visualRadius: 1.45,
    initialAngle: 2.15,
    modelPath: `${assets}/p-4d83fa21.planet`,
  },
  {
    id: 1, sequence: '03', projectInfo: 'Distributed Checkout',
    previewDescription: 'Coordinating checkout across services and failures.',
    category: 'Distributed systems', kind: 'University project', year: '2026',
    summary: 'Keeping orders, stock, and payments in sync—even when a service fails.',
    description: 'Implemented asynchronous checkout orchestration with two-phase commit and sagas across order, stock, and payment services. Added recovery workers, idempotent checkout handling, and tests for duplicate requests and compensation after failed payments.',
    role: 'Software development', technologies: ['Python', 'FastAPI', 'Redis'],
    takeaway: 'Coordination · Recovery · Idempotency', visual: 'checkout',
    accent: '#edb684', featured: true,
    orbitalRadius: 22, orbitalSpeed: 0.07, visualRadius: 1.8,
    initialAngle: -2.5,
    modelPath: `${assets}/p-c7b5e103.planet`,
  },
  {
    id: 4, sequence: '04', projectInfo: 'Aperture',
    previewDescription: 'Collaborative coding in a remote IDE.',
    category: 'Developer tooling', kind: 'University project', year: '2025',
    summary: 'A shared workspace for building software, wherever the team is.',
    description: 'Developed role-specific views in a React/Tauri desktop client for a collaborative remote IDE prototype. The team prototype supported remote builds in Docker/Nix sessions and preserved both users’ edits in a two-client concurrent typing experiment.',
    role: 'Frontend development', technologies: ['React', 'Tauri', 'Docker'],
    takeaway: 'Collaboration · Remote builds · Developer experience', visual: 'editor',
    accent: '#96c9c2', featured: true,
    orbitalRadius: 28, orbitalSpeed: 0.05, visualRadius: 1.5,
    initialAngle: 2.95,
    modelPath: `${assets}/p-a91f2d4c.planet`,
  },
  {
    id: 6, sequence: '05', projectInfo: 'TALIO',
    previewDescription: 'Keeping shared tasks synchronized across clients.',
    category: 'Collaborative applications', kind: 'University project', year: '2023',
    summary: 'Shared task boards that keep everyone on the same page.',
    description: 'Worked in a university team on a client-server task-management application. Boards contain lists, tasks, subtasks, and tags, with customizable colours and changes synchronized across connected clients. The Java client connects to a Spring server that stores the shared boards.',
    role: 'Team software development', technologies: ['Java', 'JavaFX', 'Spring'],
    accent: '#e5bf86', featured: false,
    orbitalRadius: 10, orbitalSpeed: 0.15, visualRadius: 0.85,
    initialAngle: 2.6,
    modelPath: `${assets}/p-31b8f902.planet`,
  },
  {
    id: 7, sequence: '06', projectInfo: 'Ulam Spiral',
    previewDescription: 'Revealing patterns hidden within prime numbers.',
    category: 'Mathematical visualization', kind: 'Personal project',
    summary: 'An interactive look at the patterns formed by prime numbers.',
    description: 'Created a browser-based visualization of the Ulam spiral using vanilla JavaScript and HTML. Arranging integers along a spiral and marking the primes makes surprising diagonal patterns visible.',
    role: 'Personal project', technologies: ['JavaScript', 'HTML', 'Canvas'],
    accent: '#b4a0db', featured: false,
    orbitalRadius: 6, orbitalSpeed: 0.20, visualRadius: 0.7,
    initialAngle: -1.2,
    modelPath: `${assets}/p-7c2e19a4.planet`,
  },
  {
    id: 8, sequence: '07', projectInfo: 'Chore Scheduler',
    previewDescription: 'Sharing household chores through weekly rotation.',
    category: 'Everyday tools', kind: 'Personal project',
    summary: 'A simple weekly rotation for keeping household chores fair.',
    description: 'Built a React application that rotates shared household tasks by week. A visual schedule wheel shows the assignments, with date-based rotation keeping the schedule consistent without manually reshuffling chores.',
    role: 'Personal project', technologies: ['React', 'JavaScript', 'date-fns'],
    accent: '#bdd39a', featured: false,
    orbitalRadius: 6, orbitalSpeed: 0.20, visualRadius: 0.7,
    initialAngle: 1.4,
    modelPath: `${assets}/p-d09f6a32.planet`,
  },
  {
    id: 9, sequence: '08', projectInfo: 'UnMed',
    previewDescription: 'Evaluating the quality of AI notes.',
    category: 'AI evaluation', kind: 'Codehive project', year: '2026',
    summary: 'Defining how to evaluate AI-generated clinical notes.',
    description: 'Researched and designed UnMedBench’s evaluation approach for AI-generated clinical notes, defining scoring criteria and regression checks that informed the team’s implementation. Also reviewed the existing application and translated authentication, logging, testing, and error-handling findings into a prioritized engineering backlog.',
    role: 'Evaluation design · Codehive', technologies: ['Python', 'FastAPI', 'Evaluation'],
    accent: '#89c9bd', featured: false,
    orbitalRadius: 16, orbitalSpeed: 0.10, visualRadius: 0.95,
    initialAngle: -1.8,
    modelPath: `${assets}/p-8af02c65.planet`,
  },
  {
    id: 10, sequence: '09', projectInfo: 'Boskalis SDK',
    previewDescription: 'Reusable building blocks for internal developers.',
    category: 'Developer tooling', kind: 'Industry university project', year: '2024',
    summary: 'Helping internal developers build applications with shared tools.',
    description: 'Led a five-person student team building a Python SDK with Azure and Databricks integrations, API clients, OAuth2 flows, and reusable UI components. Two teammates used the SDK to build proof-of-concept applications in one and one-and-a-half developer-days, both validated with the product manager.',
    role: 'Student team lead · Boskalis', technologies: ['Python', 'Azure', 'OAuth2'],
    accent: '#ddaa87', featured: false,
    orbitalRadius: 22, orbitalSpeed: 0.07, visualRadius: 1.0,
    initialAngle: -3.0,
    modelPath: `${assets}/p-f6250b9c.planet`,
  },
  {
    id: 11, sequence: '10', projectInfo: 'DODA',
    previewDescription: 'Deploying and observing cloud-native spam detection.',
    category: 'Cloud infrastructure', kind: 'University project', year: '2026',
    summary: 'Taking an SMS classifier from services to an observable Kubernetes deployment.',
    description: 'A university team project deploying an SMS spam checker with a Spring Boot application and Python model service. The deployment brings together Kubernetes, Helm, and Istio for service routing and canary releases, with Prometheus and Grafana for observability and Ansible for cluster provisioning.',
    role: 'Team software development', technologies: ['Kubernetes', 'Istio', 'Helm'],
    accent: '#9abada', featured: false,
    orbitalRadius: 28, orbitalSpeed: 0.05, visualRadius: 1.05,
    initialAngle: 2.65,
    modelPath: `${assets}/p-2e91c7ab.planet`,
  },
  {
    id: 12, sequence: '11', projectInfo: 'LLM Eco Tracker',
    previewDescription: 'Scheduling flexible AI work around carbon.',
    category: 'Sustainable software', kind: 'University project', year: '2026',
    summary: 'Moving flexible LLM workloads into greener electricity windows.',
    description: 'A Python library for carbon-aware LLM execution. A decorator schedules non-urgent work against grid forecasts, records estimated energy and emissions, and supports smaller-model fallbacks and per-session carbon budgets. Includes benchmark and analysis tooling to evaluate the approach.',
    role: 'Team software development', technologies: ['Python', 'EcoLogits', 'Telemetry'],
    accent: '#b4cd84', featured: false,
    orbitalRadius: 16, orbitalSpeed: 0.10, visualRadius: 0.9,
    initialAngle: 3.1,
    modelPath: `${assets}/p-60d4a8ef.planet`,
  },
  {
    id: 2, sequence: '12', projectInfo: 'Modelling Chord',
    previewDescription: 'Checking correctness in distributed ring routing.',
    category: 'Formal verification', kind: 'University research project', year: '2026',
    summary: 'Exploring what it takes for a distributed ring to find the right answer.',
    description: 'A research project modelling the Chord protocol in TLA+. The models describe lookup routing and node joins, with checks for lookup correctness, successor reachability, and eventual stabilisation after joins. The evaluation compares finger-table routing with successor-only baselines.',
    role: 'Research project', technologies: ['TLA+', 'TLC', 'Chord'],
    takeaway: 'Correctness · Routing · Model checking', visual: 'chord',
    accent: '#99c9df', featured: false,
    orbitalRadius: 10, orbitalSpeed: 0.15, visualRadius: 0.95,
    initialAngle: 0.9,
    modelPath: `${assets}/p-b3f817ce.planet`,
  }
];

// The written portfolio stays curated; the universe includes the full collection.
export const featuredProjects = projects.filter(project => project.featured);

export const experience = [
  { company: 'Codehive', role: 'Junior Software Engineer · Part-time', dates: 'Sep 2026 — Present', description: 'Continuing my software engineering work alongside my master’s studies.' },
  { company: 'Booking.com', role: 'Software Engineering Intern', dates: 'Jul — Aug 2026', description: 'Built production instrumentation and dashboards to connect feature-level resource usage with infrastructure cost.' },
  { company: 'Codehive', role: 'Junior Software Engineer · Part-time', dates: 'Oct 2024 — Jun 2026', description: 'Led development of ResumAI, an AI-assisted CV platform used by three companies. Built its frontend and document-processing workflows, and designed an evaluation approach for AI-generated clinical notes.' },
  { company: 'Boskalis', role: 'Software Engineering Intern', dates: 'Apr — Jun 2024', description: 'Led a five-person student team building a Python SDK for internal developers, including Azure/Databricks integrations, API clients, and OAuth2 flows.' },
];

export const technicalStack = [
  {
    title: 'Languages', items: [
      ['Java', 'Services / instrumentation'],
      ['Python', 'APIs / tooling'],
      ['TypeScript', 'Frontend / web apps'],
    ]
  },
  {
    title: 'Frameworks & Data', items: [
      ['React', 'Interfaces'],
      ['Django / FastAPI', 'Backend services'],
      ['Redis / Celery', 'Queues / orchestration'],
      ['PostgreSQL', 'Relational data'],
    ]
  },
  {
    title: 'Infrastructure & Tools', items: [
      ['Docker', 'Containers'],
      ['Azure', 'Cloud integrations'],
      ['Grafana', 'Observability'],
      ['Git / CI/CD', 'Delivery workflows'],
    ]
  },
];
